HAI 1.2
    I HAS A X ITZ 1
    I HAS A Y ITZ 2
    I HAS A TOP ITZ 4000000
    I HAS A FIBBERSUM ITZ 0
    I HAS A N ITZ 0
    IM IN YR LOOP UPPIN YR N WILE ALL OF DIFFRINT X AN BIGGR OF X AN TOP AN DIFFRINT Y AN BIGGR OF Y AN TOP MKAY BTW X AND Y < TOP
        BOTH SAEM MOD OF Y AN 2 AN 0, O RLY?
        YA RLY, FIBBERSUM R SUM OF FIBBERSUM AN Y
        OIC
        I HAS A Z ITZ SUM OF X AN Y
        X R Y
        Y R Z
    IM OUTTA YR LOOP
    VISIBLE FIBBERSUM BTW ITZ 4613732
KTHXBYE
