HAI 1.2
    I HAS A LIMIT ITZ 1000 BTW THIS IS THE CEILING
    I HAS A SUM ITZ 0
    I HAS A N ITZ 0
    IM IN YR LOOP UPPIN YR N WILE DIFFRINT N AN BIGGR OF N AN LIMIT BTW INCREMENTS N
        ANY OF BOTH SAEM MOD OF N AN 3 AN 0 AN BOTH SAEM MOD OF N AN 5 AN 0 MKAY
            O RLY?
            YA RLY 
                SUM R SUM OF SUM AN N
            OIC
    IM OUTTA YR LOOP
    VISIBLE SUM BTW ANSWER IS 233168
KTHXBYE
